name: “The Porter” for Git Things Done
description: >
  Opens and closes GitTD entries each day.
inputs:
  token:
    description: Usually `secrets.GITHUB_TOKEN`.
    default: ${{ github.token }}
outputs:
  today:
    description: >
      The issue number of the created issue.
      We also set `$GTD_TODAY`.
  yesterday:
    description: >
      The issue number of yesterday’s issue.
      Note, for your first day, this will be empty.
      We also set `$GTD_YESTERDAY`.
runs:
  using: node16
  main: dist/index.js

branding:
  icon: check-square
  color: green
